# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [256]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [257]:
df = pd.read_csv('AviationData.csv', encoding='latin1', low_memory=False)

In [258]:
display(df.head())
print(df.shape)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

(88889, 31)

In [259]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier',
       'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date'],
      dtype='object')

In [260]:
display(df.isnull().sum())
display(df.describe(include='all').T)

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

                          count unique             top   freq      mean        std  min  25%  50%  75%    max
Event.Id                  88889  87951  20001212X19172      3       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Investigation.Type        88889      2        Accident  85015       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Accident.Number           88889  88863      CEN22LA149      2       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Event.Date                88889  14782      1984-06-30     25       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Location                  88837  27758   ANCHORAGE, AK    434       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Country                   88663    219   United States  82248       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Latitude                  34382  25589         332739N     19       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Longitude                 34373  27154        0112457W     24       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Airport.Code              50132  10374            NONE   1488       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Airport.Name              52704  24870         Private    240       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Injury.Severity           87889    109       Non-Fatal  67357       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Aircraft.damage           85695      4     Substantial  64148       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Aircraft.Category         32287     15        Airplane  27617       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Registration.Number       87507  79104            NONE    344       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Make                      88826   8237          Cessna  22227       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Model                     88797  12318             152   2367       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Amateur.Built             88787      2              No  80312       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Number.of.Engines       82805.0    NaN             NaN    NaN  1.146585    0.44651  0.0  1.0  1.0  1.0    8.0
Engine.Type               81793     12   Reciprocating  69530       NaN        NaN  NaN  NaN  NaN  NaN    NaN
FAR.Description           32023     31             091  18221       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Schedule                  12582      3            NSCH   4474       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Purpose.of.flight         82697     26        Personal  49448       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Air.carrier               16648  13590           Pilot    258       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Total.Fatal.Injuries    77488.0    NaN             NaN    NaN  0.647855    5.48596  0.0  0.0  0.0  0.0  349.0
Total.Serious.Injuries  76379.0    NaN             NaN    NaN  0.279881   1.544084  0.0  0.0  0.0  0.0  161.0
Total.Minor.Injuries    76956.0    NaN             NaN    NaN  0.357061   2.235625  0.0  0.0  0.0  0.0  380.0
Total.Uninjured         82977.0    NaN             NaN    NaN   5.32544  27.913634  0.0  0.0  1.0  2.0  699.0
Weather.Condition         84397      4             VMC  77303       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Broad.phase.of.flight     61724     12         Landing  15428       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Report.Status             82505  17074  Probable Cause  61754       NaN        NaN  NaN  NaN  NaN  NaN    NaN
Publication.Date          75118   2924      25-09-2020  17019       NaN        NaN  NaN  NaN  NaN  NaN    NaN

In [261]:
df.describe()

       Number.of.Engines  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured
count       82805.000000          77488.000000            76379.000000          76956.000000     82977.000000
mean            1.146585              0.647855                0.279881              0.357061         5.325440
std             0.446510              5.485960                1.544084              2.235625        27.913634
min             0.000000              0.000000                0.000000              0.000000         0.000000
25%             1.000000              0.000000                0.000000              0.000000         0.000000
50%             1.000000              0.000000                0.000000              0.000000         1.000000
75%             1.000000              0.000000                0.000000              0.000000         2.000000
max             8.000000            349.000000              161.000000            380.000000       699.000000

In [262]:
pd.set_option('display.max_columns', None) 
pd.set_option('display.width', 200)

In [263]:
print(f"DataFrame shape: {df.shape}")
print(f"DataFrame columns: {df.columns.tolist()}")
df.info()

DataFrame shape: (88889, 31)
DataFrame columns: ['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [264]:
nan_summary = pd.DataFrame(df.isna().sum(), columns=['NaN Count'])
nan_summary

                        NaN Count
Event.Id                        0
Investigation.Type              0
Accident.Number                 0
Event.Date                      0
Location                       52
Country                       226
Latitude                    54507
Longitude                   54516
Airport.Code                38757
Airport.Name                36185
Injury.Severity              1000
Aircraft.damage              3194
Aircraft.Category           56602
Registration.Number          1382
Make                           63
Model                          92
Amateur.Built                 102
Number.of.Engines            6084
Engine.Type                  7096
FAR.Description             56866
Schedule                    76307
Purpose.of.flight            6192
Air.carrier                 72241
Total.Fatal.Injuries        11401
Total.Serious.Injuries      12510
Total.Minor.Injuries        11933
Total.Uninjured              5912
Weather.Condition            4492
Broad.phase.of.flight       27165
Report.Status                6384
Publication.Date            13771

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [266]:
print(df.shape)
display(df.head())
print(df.isna().sum())
print(df.duplicated().sum())

(88889, 31)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Engine.Type,FAR.Description,Schedule,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,Stinson,108-3,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,Piper,PA24-180,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Reciprocating,NaN,NaN,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,NaN,NaN,NaN,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64
0

In [267]:

print(df.columns.tolist())
display(df.head(3).T)

['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

                                      0               1               2
Event.Id                 20001218X45444  20001218X45447  20061025X01555
Investigation.Type             Accident        Accident        Accident
Accident.Number              SEA87LA080      LAX94LA336      NYC07LA005
Event.Date                   1948-10-24      1962-07-19      1974-08-30
Location                MOOSE CREEK, ID  BRIDGEPORT, CA   Saltville, VA
Country                   United States   United States   United States
Latitude                            NaN             NaN       36.922223
Longitude                           NaN             NaN      -81.878056
Airport.Code                        NaN             NaN             NaN
Airport.Name                        NaN             NaN             NaN
Injury.Severity                Fatal(2)        Fatal(4)        Fatal(3)
Aircraft.damage               Destroyed       Destroyed       Destroyed
Aircraft.Category                   NaN             NaN             NaN
Registration.Number              NC6404          N5069P          N5142R
Make                            Stinson           Piper          Cessna
Model                             108-3        PA24-180            172M
Amateur.Built                        No              No              No
Number.of.Engines                   1.0             1.0             1.0
Engine.Type               Reciprocating   Reciprocating   Reciprocating
FAR.Description                     NaN             NaN             NaN
Schedule                            NaN             NaN             NaN
Purpose.of.flight              Personal        Personal        Personal
Air.carrier                         NaN             NaN             NaN
Total.Fatal.Injuries                2.0             4.0             3.0
Total.Serious.Injuries              0.0             0.0             NaN
Total.Minor.Injuries                0.0             0.0             NaN
Total.Uninjured                     0.0             0.0             NaN
Weather.Condition                   UNK             UNK             IMC
Broad.phase.of.flight            Cruise         Unknown          Cruise
Report.Status            Probable Cause  Probable Cause  Probable Cause
Publication.Date                    NaN      19-09-1996      26-02-2007

In [268]:
text_columns = df.select_dtypes(include=['object', 'string']).columns.tolist()

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [269]:
df["Aircraft.Category"].value_counts(dropna=False)

Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

In [270]:
df["Amateur.Built"].value_counts(dropna=False)

Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

In [271]:
df["Event.Date"].head()

0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: object

In [272]:
df["Event.Date"].dtype

dtype('O')

In [273]:
df.shape

(88889, 31)

In [274]:
cols = ['Event.Date', 'Make', 'Model', 'Amateur.Built', 'Aircraft.Category',
        'Number.of.Engines', 'Engine.Type', 'Aircraft.damage', 'Injury.Severity',
        'Total.Fatal.Injuries', 'Total.Serious.Injuries',
        'Total.Minor.Injuries', 'Total.Uninjured']

for col in ['Amateur.Built', 'Aircraft.Category', 'Number.of.Engines',
            'Engine.Type', 'Aircraft.damage']:
    print(f"Column: {col}")
    print(df[col].value_counts(dropna=False))

print(df['Injury.Severity'].value_counts(dropna=False).head(10))

Column: Amateur.Built
Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64
Column: Aircraft.Category
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64
Column: Number.of.Engines
Number.of.Engines
1.0    69582
2.0    11079
NaN     6084
0.0     1226
3.0      483
4.0      431
8.0        3
6.0        1
Name: count, dtype: int64
Column: Engine.Type
Engine.Type
Reciprocating      69530
NaN                 7096
Turbo Shaft         3609
Turbo Prop          3391
Turbo Fan           2481
Unknown             2051
Turbo Jet            703
Geared Turbofan       12
Electric              10
LR                     2
NONE                   2
Hybrid Rocket          1
UNK                    1
Name: count, dtype: int64
Column: Aircraft.damage
Aircraft.damage
Substantial    64148
Destroyed      18623
NaN             3194
Minor           2805
Unknown          119
Name: count, dtype: int64
Injury.Severity
Non-Fatal    67357
Fatal(1)      6167
Fatal         5262
Fatal(2)      3711
Incident      2219
Fatal(3)      1147
NaN           1000
Fatal(4)       812
Fatal(5)       235
Minor          218
Name: count, dtype: int64

In [275]:
df['Event.Date'] = pd.to_datetime(df['Event.Date'], errors='coerce')
df['Year'] = df['Event.Date'].dt.year


df = df[df['Year'] >= 1983].copy()

print("Rows after filtering for Year:", len(df))
print("Year range:", df['Year'].min(), "-", df['Year'].max())

Rows after filtering for Year: 85289
Year range: 1983 - 2022

In [276]:
if "Amateur.Built" in df.columns:
    df["Amateur.Built"] = df["Amateur.Built"].astype(str).str.strip().str.lower()
    df = df[~df["Amateur.Built"].isin(["yes", "y", "true"])].copy()

In [277]:
for col in ['Make', 'Model']:
    if col in df.columns:
        df[col] = df[col].str.strip().str.upper().astype('string').replace('', pd.NA)


#Standardize 'Amateur.Built' column
df['Amateur.Built'] = df['Amateur.Built'].str.strip().str.upper().astype('string')
df['Aircraft.damage'] = df['Aircraft.damage'].str.strip().str.upper().astype('string')


df = df.dropna(subset=['Make', 'Model', 'Amateur.Built', 'Aircraft.damage'])

print("Rows after cleaning Make and Model:", len(df))
print(df[['Make', 'Model', 'Amateur.Built', 'Aircraft.damage']].head())

Rows after cleaning Make and Model: 73898
        Make       Model Amateur.Built Aircraft.damage
3601  CESSNA        182P            NO     SUBSTANTIAL
3602  CESSNA       182RG            NO     SUBSTANTIAL
3603  CESSNA        182P            NO     SUBSTANTIAL
3604   PIPER  PA-28R-200            NO     SUBSTANTIAL
3605  CESSNA         140            NO     SUBSTANTIAL

In [278]:
df = df[df['Amateur.Built'] == 'NO'].copy()

print("Rows after filtering for Amateur.Built == 'NO':", len(df))
print(df['Amateur.Built'].value_counts(dropna=False))

Rows after filtering for Amateur.Built == 'NO': 73818
Amateur.Built
NO    73818
Name: count, dtype: Int64

In [279]:
#Injury Severity Count and cleaning
df['Injury.Severity'] = df['Injury.Severity'].str.strip().str.upper().astype('string')

In [280]:
make_counts = df.groupby("Make").size().reset_index(name="count")
make_counts = make_counts[make_counts["count"] >= 10]

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [281]:
df["Injury.Severity"].value_counts(dropna=False)

Injury.Severity
NON-FATAL     57075
FATAL(1)       4606
FATAL          4433
FATAL(2)       3127
INCIDENT       1257
              ...
FATAL(199)        1
FATAL(89)         1
FATAL(135)        1
FATAL(37)         1
FATAL(43)         1
Name: count, Length: 103, dtype: Int64

In [282]:
df["Total.occupants"] = df[injury_cols].sum(axis=1)

In [283]:
injury_cols = ['Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured']

for col in injury_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)


df["Total.occupants"] = df[injury_cols].sum(axis=1)


#Fatal injuries

df['Fatal.Serious.Count'] = (
    df['Total.Serious.Injuries'].fillna(0) + 
    df['Total.Fatal.Injuries'].fillna(0)
)


df['Fatal.Serious.Rate'] = (
    df['Fatal.Serious.Count'] / df['Total.occupants']
).where(df['Total.occupants'] > 0)



df['Fatal.Serious.Flag'] = (
    df['Fatal.Serious.Count'] > 0
).astype('boolean')



print(df[
    ['Total.occupants', 'Fatal.Serious.Count', 'Fatal.Serious.Rate', 'Fatal.Serious.Flag']
].head())

      Total.occupants  Fatal.Serious.Count  Fatal.Serious.Rate  Fatal.Serious.Flag
3601                4                    0                 0.0               False
3602                2                    0                 0.0               False
3603                1                    0                 0.0               False
3604                2                    0                 0.0               False
3605                2                    0                 0.0               False

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [284]:
df["Aircraft.damage"].value_counts(dropna=False)

Aircraft.damage
SUBSTANTIAL    55664
DESTROYED      15456
MINOR           2582
UNKNOWN          116
Name: count, dtype: Int64

In [285]:
if "Aircraft.damage" in df.columns:
    df["Aircraft.damage"] = df["Aircraft.damage"].astype(str).str.strip().str.lower()
    df["Destroyed.Flag"] = df["Aircraft.damage"].str.contains("destroyed", case=False, na=False).astype(int)

In [286]:
df["Aircraft.Size"] = np.where(df["Total.occupants"] <= 20, "Small", "Large")

In [287]:
print(df[[
    "Year", "Make", "Model", "Total.occupants", 
    "Fatal.Serious.Count", "Fatal.Serious.Rate", 
    "Destroyed.Flag", "Aircraft.Size"
]].head())

      Year    Make       Model  Total.occupants  Fatal.Serious.Count  Fatal.Serious.Rate  Destroyed.Flag Aircraft.Size
3601  1983  CESSNA        182P                4                    0                 0.0               0         Small
3602  1983  CESSNA       182RG                2                    0                 0.0               0         Small
3603  1983  CESSNA        182P                1                    0                 0.0               0         Small
3604  1983   PIPER  PA-28R-200                2                    0                 0.0               0         Small
3605  1983  CESSNA         140                2                    0                 0.0               0         Small

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [288]:
#Identify cleaning tasks

df["Make"].head()
df["Make"].value_counts().head(20)

Make
CESSNA               25491
PIPER                13983
BEECH                 5024
BELL                  2534
BOEING                1552
MOONEY                1261
ROBINSON              1176
GRUMMAN               1055
BELLANCA               973
HUGHES                 863
SCHWEIZER              744
AIR TRACTOR            667
AERONCA                605
MAULE                  569
CHAMPION               501
MCDONNELL DOUGLAS      435
STINSON                421
AERO COMMANDER         407
LUSCOMBE               387
DE HAVILLAND           368
Name: count, dtype: Int64

In [289]:
df["Make"].isna().sum()

0

In [290]:
df["Make"] = df["Make"].astype(str).str.strip()
df["Make"] = df["Make"].str.title()

In [291]:
df["Make"] = df["Make"].replace({
    "Boeing Co": "Boeing",
    "Boeing Company": "Boeing",
    "Airbus Industrie": "Airbus",
    "Airbus Industrie A.": "Airbus",
    "Cessna Aircraft Co": "Cessna",
    "Cessna Aircraft Company": "Cessna",
    "Piper Aircraft": "Piper"
})

In [292]:
df = df[df["Make"].notna()]
df = df[df["Make"] != "nan"]
df = df[df["Make"] != ""]

In [293]:
make_counts = (
    df.groupby("Make")
      .size()
      .reset_index(name="accidents")
      .sort_values("accidents", ascending=False)
)

make_counts.head(20)

                   Make  accidents
437              Cessna      25527
1285              Piper      13990
292               Beech       5024
301                Bell       2534
340              Boeing       1555
1163             Mooney       1261
1406           Robinson       1176
829             Grumman       1055
323            Bellanca        973
925              Hughes        863
1484          Schweizer        744
96          Air Tractor        667
43              Aeronca        605
1100              Maule        569
454            Champion        501
1112  Mcdonnell Douglas        435
1596            Stinson        421
24       Aero Commander        407
1076           Luscombe        387
572        De Havilland        368

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [294]:
df["Model"].isna().sum()
df["Model"].value_counts().head(20)

Model
152          2217
172          1630
172N         1084
PA-28-140     859
172M          758
150           745
172P          663
182           612
180           595
PA-18-150     554
PA-18         551
150M          550
PA-28-180     546
PA-28-161     523
PA-28-181     506
206B          487
A36           432
150L          432
G-164A        428
PA-38-112     421
Name: count, dtype: Int64

In [295]:
df["Model"] = df["Model"].astype(str).str.strip()
df["Model"] = df["Model"].replace({"nan": "Unknown", "": "Unknown"})

In [296]:
df["Plane.Type"] = (
    df["Make"].fillna("Unknown").astype(str).str.strip().str.title()
    + " "
    + df["Model"].fillna("Unknown").astype(str).str.strip()
).str.replace(r"\s+", " ", regex=True)

In [297]:
plane_counts = df.groupby("Plane.Type").size().reset_index(name="count")
plane_counts.sort_values("count", ascending=False).head(20)

           Plane.Type  count
3105       Cessna 152   2217
3129       Cessna 172   1627
3180      Cessna 172N   1083
7699  Piper PA-28-140    859
3178      Cessna 172M    758
3078       Cessna 150    745
3183      Cessna 172P    663
3234       Cessna 182    612
3212       Cessna 180    594
3104      Cessna 150M    550
7596      Piper PA-18    548
7604  Piper PA-18-150    547
7709  Piper PA-28-180    546
7708  Piper PA-28-161    519
7715  Piper PA-28-181    503
1867        Bell 206B    480
3103      Cessna 150L    432
7848  Piper PA-38-112    421
1427        Beech A36    401
3075       Cessna 140    383

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [298]:
# Engine type
df["Engine.Type"] = df["Engine.Type"].astype(str).str.strip()
df["Engine.Type"] = df["Engine.Type"].replace({"nan": "Unknown", "": "Unknown"})

# Weather condition
df["Weather.Condition"] = df["Weather.Condition"].astype(str).str.strip()
df["Weather.Condition"] = df["Weather.Condition"].replace({"nan": "Unknown", "": "Unknown"})

# Engine count
df["Number.of.Engines"] = pd.to_numeric(df["Number.of.Engines"], errors="coerce")
df["Number.of.Engines"] = df["Number.of.Engines"].fillna(df["Number.of.Engines"].median())

# Purpose of flight
df["Purpose.of.flight"] = df["Purpose.of.flight"].astype(str).str.strip()
df["Purpose.of.flight"] = df["Purpose.of.flight"].replace({"nan": "Unknown", "": "Unknown"})

# Flight phase
df["Broad.phase.of.flight"] = df["Broad.phase.of.flight"].astype(str).str.strip()
df["Broad.phase.of.flight"] = df["Broad.phase.of.flight"].replace({"nan": "Unknown", "": "Unknown"})

In [299]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     42
Country                     195
Latitude                  44610
Longitude                 44617
Airport.Code              31517
Airport.Name              29641
Injury.Severity             483
Aircraft.damage               0
Aircraft.Category         49823
Registration.Number        1040
Make                          0
Model                         0
Amateur.Built                 0
Number.of.Engines             0
Engine.Type                   0
FAR.Description           50076
Schedule                  63882
Purpose.of.flight             0
Air.carrier               59939
Total.Fatal.Injuries          0
Total.Serious.Injuries        0
Total.Minor.Injuries          0
Total.Uninjured               0
Weather.Condition             0
Broad.phase.of.flight         0
Report.Status              4961
Publication.Date          12296
Year                          0
Total.occupants               0
Fatal.Serious.Count           0
Fatal.Serious.Rate          655
Fatal.Serious.Flag            0
Destroyed.Flag                0
Aircraft.Size                 0
Plane.Type                    0
dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [300]:
missing_values = df.isnull().mean()
drop_cols = missing_values[missing_values > 0.7].index.tolist()
df = df.drop(columns=drop_cols)

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [301]:
df.to_csv("AviationData_Cleaned.csv", index=False)